- platform: flux
  mode: mired
  disable_brightness_adjust: True
  lights:
    - light.tradfri_bulb_gu10_ws_400lm
    - light.tradfri_bulb_gu10_ws_400lm_2
    - light.tradfri_bulb_gu10_ws_400lm_3
    - light.tradfri_bulb_gu10_ws_400lm_4
    - light.tradfri_bulb_gu10_ws_400lm_5
    - light.tradfri_bulb_gu10_ws_400lm_6
