- platform: command_line
  switches:
    foscam_motion:
      command_on: !secret foscam_command_on
      command_off: !secret foscam_command_off
      command_state: !secret foscam_command_state
      value_template: '{{ value == "1" }}'
