- name: Wohnzimmer normal
  entities:
    group.wohnzimmer:
      state: on
      transition: 2
      brightness_pct: 80
- name: Wohnzimmer gedimmt
  entities:
    group.wohnzimmer:
      state: on
      transition: 2
      brightness_pct: 10
- name: Baden
  entities:
    climate.meq1884545:
      temperature: 30
