- name: Wohnzimmer normal
  entities:
    group.wohnzimmer:
      state: on
      transition: 2
      brightness_pct: 80
- name: Wohnzimmer gedimmt
  entities:
    group.wohnzimmer:
      state: on
      transition: 9
      brightness_pct: 10
- name: Baden
  entities:
    climate.meq1884545:
      temperature: 30
- name: Fernsehen
  entities:
    script.fernsehen_remote: True
- name: Switch
  entities:
    script.switch_remote: True
