- alias: Autostart Fluxer
  trigger:
  - platform: homeassistant
    event: start
  action:
  - service: switch.turn_on
    entity_id: switch.flux

- alias: Licht an wenn dunkel
  trigger:
    - platform: state
      entity_id: group.sebastian
      to: 'home'
  action:
    - service: light.turn_on
      entity_id: group.all_lights
    - service: notify.telegram_notify
      data:
        title: '*HA Automation*'
        message: "Licht angeschaltet, weil dunkel und zuhause"
  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
- alias: Fernbedienung an
  trigger:
    - platform: state
      entity_id: binary_sensor.zha_04f21344_1
      to: 'on'
  action:
    - service: light.turn_on
      entity_id: group.all_lights
- alias: Fernbedienung aus
  trigger:
    - platform: state
      entity_id: binary_sensor.zha_04f21344_1
      to: 'off'
  action:
    - service: light.turn_off
      entity_id: group.all_lights
