- alias: Autostart Fluxer
  trigger:
  - platform: homeassistant
    event: start
  action:
  - service: switch.turn_on
    entity_id: switch.flux

- alias: Licht an wenn dunkel
  trigger:
    - platform: state
      entity_id: group.sebastian
      to: 'home'
  action:
    - service: light.turn_on
      entity_id: group.all_lights
    - service: notify.telegram_notify
      data:
        title: '*HA Automation*'
        message: "Licht angeschaltet, weil dunkel und zuhause"
  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
