- alias: Fernseher aus bei nicht nutzung
  trigger:
    - platform: state
      entity_id: media_player.wohnzimmer
      to: 'off'
      for:
        minutes: 10
  action:
    - service: switch.turn_off
      entity_id: switch.unterhaltung
    - service: notify.telegram_notify
      data:
        title: '*HA Automation*'
        message: "Fernseher abgeschaltet, zu lange nicht genutzt"

- alias: Fernseher aus wenn weg
  trigger:
    - platform: state
      entity_id: group.sebastian
      to: 'not_home'
  action:
    - service: switch.turn_off
      entity_id: switch.unterhaltung
    - service: notify.telegram_notify
      data:
        title: '*HA Automation*'
        message: "Fernseher abgeschaltet, nicht zuhause"
  condition:
    - condition: state
      entity_id: switch.unterhaltung
      state: 'on'


