- platform: travisci
  api_key: !secret github_key
  repository:
    - home-assistant-config
  branch:
    - master
  monitored_conditions:
    - last_build_state
    - state
- platform: yr
  monitored_conditions:
    - temperature
    - symbol
    - pressure
    - humidity
