homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 51.20407285929176
  longitude: 6.766530145921919
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Berlin
  # Customization file
  customize: !include customize.yaml

updater:
  reporting: false

logger:
  default: info

device_sun_light_trigger:
  device_group: group.sebastian
  light_group: group.all_lights

proximity:
  home: 
    devices:
      - group.sebastian
    tolerance: 50
    unit_of_measurement: km

frontend:

config:

http:
  api_password: !secret http_password
  base_url: ha.tuxcall.de:8123

recorder:
  db_url: !secret recorder_db_url

history:

logbook:

map:

sun:

mqtt:
  broker: localhost

sensor: !include_dir_merge_list sensors/

tts:
  - platform: google

cloud:

zone: !include_dir_merge_list zones/
group: !include_dir_merge_named groups/
automation: !include_dir_merge_list automations/
scene: !include_dir_merge_list scenes/
switch: !include_dir_merge_list switches/

homekit:
  auto_start: True
  filter:
    exclude_domains:
      - automation
    exclude_entities:
      - sensor.hp_ilo_server_health
      - sensor.hp_ilo_server_health_2
      - switch.flux
      - sensor.yr_temperature

cast:
  media_player:
  - host: 192.168.113.18
  - host: 192.168.113.43

device_tracker:
  - platform: owntracks

influxdb:
  host: localhost
  username: ha
  password: !secret influx_password
  tags_attributes:
    - friendly_name
  exclude:
    entities:
      - sensor.hp_ilo_server_health
      - sensor.hp_ilo_server_health_2
      - sensor.hp_ilo_cpu_fanspeed
      - sensor.hp_ilo_cpu_fanspeed_2

telegram_bot:
  - platform: polling
    api_key: !secret telegram_api
    allowed_chat_ids:
      - 589893007
      - 659192698

notify:
  - name: telegram_notify
    platform: telegram
    chat_id: 659192698

shell_command:
  git_pull: 'bash /config/git-pull.sh'  

zha:
  usb_path: /dev/ttyUSB0
  database_path: /config/zigbee.db

homematic:
  interfaces:
    rf:
      host: 192.168.113.104
      resolvenames: xml
    ip:
      host: 192.168.113.104
      port: 2010
      resolvenames: xml

remote:
  - platform: harmony
    name: Wohnzimmer
    host: 192.168.113.40 #HarmonyHub.swapoff.de

google_assistant:
  project_id: !secret google_project
  api_key: !secret google_api
  expose_by_default: True
  exposed_domains:
    - switch
    - light
    - climate

media_player:
  - platform: panasonic_viera
    host: 192.168.113.42

light:
  - platform: group
    name: Wohnzimmer Licht
    entities:
      - light.ikea_of_sweden_tradfri_bulb_gu10_ws_400lm_fec20325_1
      - light.ikea_of_sweden_tradfri_bulb_gu10_ws_400lm_fec301bb_1
      - light.ikea_of_sweden_tradfri_bulb_gu10_ws_400lm_fee4553f_1
  - platform: group
    name: Schlafzimmer Licht
    entities:
      - light.ikea_of_sweden_tradfri_bulb_gu10_ws_400lm_febffce9_1
      - light.ikea_of_sweden_tradfri_bulb_gu10_ws_400lm_fec06a91_1
      - light.ikea_of_sweden_tradfri_bulb_gu10_ws_400lm_fec36883_1
  - platform: group
    name: Flur Licht
    entities:
      - light.philips_lct015_04163ef5_11
#  - platform: group
#    name: Bad Licht
#    entities:
  - platform: group
    name: Küche Licht
    entities:
      - light.philips_lst002_04499287_11


lovelace:
  mode: yaml

script:
  flur_an:
    alias: Flur an
    sequence:
      - service: light.turn_on
        data_template:
          entity_id: light.flur_licht
          rgb_color: ["{{ range(0,255) | random }}","{{ range(0,255) | random }}","{{ range(0,255) | random }}"]
          transition: 60
      - service: script.turn_on
        data:
          entity_id: script.flur_loop
  flur_loop:
    sequence:
      - delay:
          # time for flash light off
          seconds: 61
      - alias: loop_room1
        service: script.turn_on
        data:
          entity_id: script.flur_an
