flur:
  name: Flur
  entities:
    - group.flur_sensoren
    - group.flur_licht
    - group.flur_geraete
  
wohnzimmer:
  name: Wohnzimmer
  entities:
    - group.wohnzimmer_sensoren
    - light.fwohnzimmer_licht
    - group.wohnzimmer_geraete

schlafzimmer:
  name: Schlafzimmer
  entities:
    - group.schlafzimmer_sensoren
    - light.schlafzimmer_licht
    - group.schlafzimmer_geraete

bad:
  name: Bad
  entities:
    - group.bad_sensoren
    - licht.bad_licht
    - group.bad_geraete

kueche:
  name: Küche
  entities:
    - group.kueche_sensoren
    - licht.kueche_licht
    - group.kueche_geraete

flur_sensoren:
  name: Flur Sensoren
  entities:
    - binary_sensor.r_flur
flur_geraete:

schlafzimmer_sensoren:
  name: Schlafzimmer Geräte
  entities:
    - sensor.luftdruck_schlafzimmer
    - sensor.luftfeuchtigkeit_schlafzimmer
    - sensor.temperatur_schlafzimmer
    - binary_sensor.r_schlafzimmer
schlafzimmer_geraete:
  name: Schlafzimmer Geräte
  entities:
    - media_player.schlafzimmer

wohnzimmer_geraete:
  name: Wohnzimmer
  entities:
    - switch.unterhaltung
    - media_player.wohnzimmer
    - remote.wohnzimmer
    - media_player.panasonic_viera_tv
wohnzimmer_sensoren:
  name: Wohnzimmer
  entities:
    - binary_sensor.f_wohnzimmer
    - sensor.luftdruck_wohnzimmer
    - sensor.luftfeuchtigkeit_wohnzimmer
    - sensor.temperatur_wohnzimmer
    - binary_sensor.r_wohnzimmer

kueche_geraete:
  name: Küche Geräte
  entities:
    - switch.waschmaschine
kueche_sensoren:
  name: Küche Sensoren
  entities:
    - sensor.luftdruck_kueche
    - sensor.luftfeuchtigkeit_kueche
    - sensor.temperatur_kueche

bad_geraete:
bad_sensoren:
  name: Bad Sensoren
  entities:
    - sensor.luftdruck_bad
    - sensor.luftfeuchtigkeit_bad
    - sensor.temperatur_bad
