schlafzimmer:
  entities:
    - light.tradfri_bulb_gu10_ws_400lm
    - light.tradfri_bulb_gu10_ws_400lm_2
    - light.tradfri_bulb_gu10_ws_400lm_3
wohnzimmer:
  entities:
    - light.tradfri_bulb_gu10_ws_400lm_4
    - light.tradfri_bulb_gu10_ws_400lm_5
    - light.tradfri_bulb_gu10_ws_400lm_6
