schlafzimmer:
  name: Schlafzimmer
  entities:
    - light.ikea_of_sweden_tradfri_bulb_gu10_ws_400lm_febffce9_1
    - light.ikea_of_sweden_tradfri_bulb_gu10_ws_400lm_fec06a91_1
    - light.ikea_of_sweden_tradfri_bulb_gu10_ws_400lm_fec36883_1
    - climate.t_schlafzimmer
    - sensor.luftdruck_schlafzimmer
    - sensor.luftfeuchtigkeit_schlafzimmer
    - sensor.temperatur_schlafzimmer
wohnzimmer:
  name: Wohnzimmer Licht
  entities:
    - light.ikea_of_sweden_tradfri_bulb_gu10_ws_400lm_fec20325_1
    - light.ikea_of_sweden_tradfri_bulb_gu10_ws_400lm_fec301bb_1
    - light.ikea_of_sweden_tradfri_bulb_gu10_ws_400lm_fee4553f_1
wohnzimmer_geraete:
  name: Wohnzimmer
  entities:
    - switch.unterhaltung
    - media_player.wohnzimmer
    - remote.wohnzimmer
    - climate.t_wohnzimmer
    - binary_sensor.f_wohnzimmer
    - sensor.luftdruck_wohnzimmer
    - sensor.luftfeuchtigkeit_wohnzimmer
    - sensor.temperatur_wohnzimmer
kueche:
  name: K端che
  entities:
    - climate.t_kueche
    - switch.waschmaschine
    - sensor.luftdruck_k端che
    - sensor.luftfeuchtigkeit_k端che
    - sensor.temperatur_k端che
bad:
  name: Bad
  entities:
    - climate.t_bad
    - sensor.luftdruck_bad
    - sensor.luftfeuchtigkeit_bad
    - sensor.temperatur_bad
