schlafzimmer:
  entities:
    - light.ikea_of_sweden_tradfri_bulb_gu10_ws_400lm_febffce9_1
    - light.ikea_of_sweden_tradfri_bulb_gu10_ws_400lm_fec06a91_1
    - light.ikea_of_sweden_tradfri_bulb_gu10_ws_400lm_fec36883_1
wohnzimmer:
  entities:
    - light.ikea_of_sweden_tradfri_bulb_gu10_ws_400lm_fec20325_1
    - light.ikea_of_sweden_tradfri_bulb_gu10_ws_400lm_fec301bb_1
    - light.ikea_of_sweden_tradfri_bulb_gu10_ws_400lm_fee4553f_1
