default_view:
  name: Home
  view: yes
  entities:
    - group.schlafzimmer
    - group.wohnzimmer
    - group.wohnzimmer_geräte
    - group.sebastian
    - group.kueche
    - group.bad
    - group.heizung
    - sun.sun
    - sensor.yr_symbol
    - sensor.yr_temperature

switches_view:
  name: Schalter
  view: yes
  entities:
    -  group.all_switches

licht_view:
  name: Licht
  view: yes
  entities:
    -  group.all_lights

tracker_view:
  name: Presence
  view: yes
  entities:
    -  group.all_devices

automation_view:
  name: automation
  view: yes
  entities:
    -  group.all_automations
