default_view:
  name: Home
  view: yes
  entities:
    - group.schlafzimmer
    - group.wohnzimmer
    - group.wohnzimmer_geraete
    - group.sebastian
    - group.kueche
    - group.bad
    - group.heizung
    - group.flur
    - sun.sun
    - sensor.yr_symbol
    - sensor.yr_temperature
    - binary_sensor.f_haus
    - sensor.download_iperf_he_net

all_view:
  name: Alles
  view: yes
  entities:
    -  group.all_devices
switches_view:
  name: Schalter
  view: yes
  entities:
    -  group.all_switches

licht_view:
  name: Licht
  view: yes
  entities:
    -  group.all_lights

tracker_view:
  name: Presence
  view: yes
  entities:
    -  group.all_devices

automation_view:
  name: automation
  view: yes
  entities:
    -  group.all_automations
