default_view:
  name: Home
  view: yes
  entities:
    - group.schlafzimmer
    - group.wohnzimmer
    - group.sebastian
    - device_tracker.apple_watchvonsebastian
    - device_tracker.iphonevebastian
    - device_tracker.iphonevonsebastiancc
    - sun.sun
    - sensor.temperatur
    - sensor.luftdruck
    - sensor.luftfeuchtigkeit
    - switch.fernseher
    - switch.waschmaschine
    - media_player.wohnzimmer
    - sensor.yr_symbol
    - sensor.yr_temperature
    - sensor.dusseldorf_volksgarten_to_solingen_hbf
    - camera.foscam_camera
    - climate.000393c994ddf2
    - climate.meq1884545

switches_view:
  name: Schalter
  view: yes
  entities:
    -  group.all_switches

licht_view:
  name: Licht
  view: yes
  entities:
    -  group.all_lights

tracker_view:
  name: Presence
  view: yes
  entities:
    -  group.all_devices

automation_view:
  name: automation
  view: yes
  entities:
    -  group.all_automations
